FROM python:3.9-alpine
WORKDIR /app
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
# Installo requests singolarmente per problemi
RUN pip install requests

EXPOSE 5000
COPY . .
CMD ["flask", "run"]