FROM python:3.9-alpine
WORKDIR /app
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install --no-cache-dir \
    opentelemetry-distro==0.47b0 \
    opentelemetry-exporter-otlp==1.26.0 \
    opentelemetry-instrumentation-flask==0.47b0 \
    opentelemetry-instrumentation-requests==0.47b0

EXPOSE 5000
COPY . .
CMD ["flask", "run"]